# Generated by Django 4.2.11 on 2025-04-10 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('volume', models.PositiveIntegerField(help_text='Объём в литрах')),
                ('layers', models.PositiveSmallIntegerField(choices=[(1, '1-слойный'), (2, '2-слойный'), (3, '3-слойный')])),
                ('length', models.PositiveIntegerField(help_text='Длина в см')),
                ('width', models.PositiveIntegerField(help_text='Ширина в см')),
                ('height', models.PositiveIntegerField(help_text='Высота в см')),
                ('diameter', models.PositiveIntegerField(help_text='Диаметр крышки в см')),
                ('thickness', models.CharField(help_text="Толщина стенки, например '5–7 мм'", max_length=20)),
                ('price', models.PositiveIntegerField(help_text='Цена в сомони')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.product')),
            ],
        ),
    ]
