# Generated by Django 4.2.11 on 2025-04-24 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_orderrequest_email_orderrequest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.product'),
        ),
    ]
